export default {
  avatarUpload: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    maxWidth: 160,
    height: 160,
    margin: '0 auto',
    mb: 2,
  },
  avatarEdit: {
    position: 'absolute',
    right: 12,
    zIndex: 1,
    top: 10,
  },
  input: {
    display: 'none',
  },
  label: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 34,
    height: 34,
    mb: 0,
    borderRadius: '100%',
    background: '#FFFFFF',
    border: '1px solid transparent',
    boxShadow: '0px 2px 4px 0px rgba(0, 0, 0, 0.12)',
    cursor: 'pointer',
    fontWeight: 'normal',
    transition: 'all 0.2s ease-in-out',
    '&:hover': {
      background: '#f1f1f1',
      borderColor: '#d6d6d6',
    },
    '&:after': {
      position: 'absolute',
      top: 10,
      left: 0,
      right: 0,
      textAlign: 'center',
      margin: 'auto',
    },
  },
  avatarDelete: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    left: 12,
    zIndex: 1,
    top: 10,
    width: 34,
    height: 34,
    marginBottom: 0,
    borderRadius: '100%',
    background: '#FFFFFF',
    border: '1px solid transparent',
    boxShadow: '0px 2px 4px 0px rgb(0 0 0 / 12%)',
    cursor: 'pointer',
    fontWeight: 'normal',
    transition: 'all 0.2s ease-in-out',
    '&:hover': {
      background: '#f1f1f1',
      borderColor: '#d6d6d6',
    },
    '&:after': {
      textAlign: 'center',
      margin: 'auto',
      position: 'absolute',
      top: 10,
      left: 0,
      right: 0,
    },
  },
  avatarPreview: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: 160,
    height: 160,
    position: 'relative',
    borderRadius: '100%',
    border: '6px solid #F8F8F8',
    boxShadow: '0px 2px 4px 0px rgba(0, 0, 0, 0.1)',
  },
  image: {
    width: '100%',
    height: '100%',
    borderRadius: '100%',
  },
}
